# -*- coding: utf-8 -*-
"""VisionTransformer(ViT)_PyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsFBK4HCIwMRYq9oQHT48tEtL5CtswZh

# Install Required Libraries
"""

!pip install transformers datasets torchvision

from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import DataLoader

from transformers import ViTImageProcessor

# Load processor for normalization
processor = ViTImageProcessor.from_pretrained("google/vit-base-patch16-224-in21k")

# Define transforms using processor config
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=processor.image_mean, std=processor.image_std)
])

# Load datasets
train_dataset = ImageFolder("/content/drive/MyDrive/ComputerVision/ViT_dataset/train", transform=transform)
val_dataset = ImageFolder("/content/drive/MyDrive/ComputerVision/ViT_dataset/test", transform=transform)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

"""# Load Pretrained ViT Model for Classification"""

from transformers import ViTForImageClassification


num_labels = len(train_dataset.classes)

model = ViTForImageClassification.from_pretrained(
    "google/vit-base-patch16-224-in21k",
    num_labels=num_labels,
    ignore_mismatched_sizes=True
)

"""# **Define** Optimizer, Loss, and Training"""

import torch
from torch import nn
from torch.optim import Adam

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr=5e-5)

"""# Training Loop"""

for epoch in range(5):  # Set your number of epochs
    model.train()
    total_loss = 0
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(pixel_values=images)
        loss = criterion(outputs.logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss / len(train_loader)}")

"""# Evaluation (Validation Accuracy)"""

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(pixel_values=images)
        _, preds = torch.max(outputs.logits, 1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

print(f"Validation Accuracy: {correct / total:.2%}")